config/routes.rb
Mediapackapp::Application.routes.draw do

  resources :epks

  resources :fact_sheets

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users
  
  root 'welcome#home'
    get 'plans' => 'welcome#plans'
    get 'terms' => 'welcome#terms'
    get 'guides' => 'welcome#guides'
    get 'demos' => 'welcome#demos'
    
    get "dashboard/index"
    get 'construct' => 'dashboard#construct'
  
  
  
  match ':controller(/:action(/:id(.:format)))', :via => :get
    

end

app/models/epk.rb
class Epk < ActiveRecord::Base
end

app/models/fact_sheet.rb
class FactSheet < ActiveRecord::Base

  belongs_to :user

  validates_uniqueness_of :vanity_url

  validates :first_name, :last_name, :vanity_url, :client_city, :country, presence: true   

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
  
  # this is how we control access via cancan
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  before_create :set_default_role
  has_one :fact_sheet # Generally, user will have only one fact sheet
  
  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
  
  
  # validating reg_code existence and length

  validates :reg_code, presence: true, inclusion: { in: %W(seiob14s seiob14j seiob14c nsfyb14), message: "Code is not included in the list" }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_filter :configure_permitted_parameters, if: :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :reg_code
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
 
  helper_method :resource, :resource_name, :devise_mapping

  def after_sign_in_path_for(user)
    ((current_user.sign_in_count == 1) ? new_fact_sheet_path : dashboard_index_path )
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
  end

  def construct
  end

end

app/controllers/epks_controller.rb
class EpksController < ApplicationController
  before_action :set_epk, only: [:show, :edit, :update, :destroy]

  # GET /epks
  # GET /epks.json
  def index
    @epks = Epk.all
  end

  # GET /epks/1
  # GET /epks/1.json
  def show
  end

  # GET /epks/new
  def new
    @epk = Epk.new
  end

  # GET /epks/1/edit
  def edit
  end

  # POST /epks
  # POST /epks.json
  def create
    @epk = Epk.new(epk_params)

    respond_to do |format|
      if @epk.save
        format.html { redirect_to @epk, notice: 'Epk was successfully created.' }
        format.json { render action: 'show', status: :created, location: @epk }
      else
        format.html { render action: 'new' }
        format.json { render json: @epk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epks/1
  # PATCH/PUT /epks/1.json
  def update
    respond_to do |format|
      if @epk.update(epk_params)
        format.html { redirect_to @epk, notice: 'Epk was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @epk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epks/1
  # DELETE /epks/1.json
  def destroy
    @epk.destroy
    respond_to do |format|
      format.html { redirect_to epks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epk
      @epk = Epk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epk_params
      params.require(:epk).permit(:name, :user_id)
    end
end

app/controllers/fact_sheets_controller.rb
class FactSheetsController < ApplicationController
  before_action :set_fact_sheet, only: [:show, :edit, :update, :destroy]

  # GET /fact_sheets
  # GET /fact_sheets.json
  def index
    @fact_sheets = FactSheet.all
  end

  # GET /fact_sheets/1
  # GET /fact_sheets/1.json
  def show
  end

  # GET /fact_sheets/new
  def new
    @fact_sheet = FactSheet.new
  end

  # GET /fact_sheets/1/edit
  def edit
    
  end

  # POST /fact_sheets
  # POST /fact_sheets.json
  def create
    @fact_sheet = FactSheet.new(fact_sheet_params)

    respond_to do |format|
      if @fact_sheet.save
        format.html { redirect_to @fact_sheet, notice: 'Fact sheet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @fact_sheet }
      else
        format.html { render action: 'new' }
        format.json { render json: @fact_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fact_sheets/1
  # PATCH/PUT /fact_sheets/1.json
  def update
    respond_to do |format|
      if @fact_sheet.update(fact_sheet_params)
        format.html { redirect_to @fact_sheet, notice: 'Fact sheet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @fact_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fact_sheets/1
  # DELETE /fact_sheets/1.json
  def destroy
    @fact_sheet.destroy
    respond_to do |format|
      format.html { redirect_to fact_sheets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact_sheet
      @fact_sheet = FactSheet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fact_sheet_params
      params.require(:fact_sheet).permit(:vanity_url, :country, :first_name, :last_name, :middle_initial, :p_k_a, :professional_business_type, :client_tel_mobile, :client_tel_work, :client_tel_alt, :client_email_alt, :client_url, :client_street_address_1, :client_street_address_2, :client_unit_number, :client_city, :client_county, :client_state, :client_postal_code, :company_name, :company_tel_main, :company_url, :company_email, :company_street_address_1, :company_street_address_2, :company_suite_number, :company_city, :company_county, :company_state, :company_postal_code)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    render( :template => 'welcome/home' )
  end
  
 

  def home
    if user_signed_in?
      redirect_to( :controller => 'dashboard', :action => 'index' )
      
      @fact_sheets = FactSheet.all
    end
    
  end

  def plans
    render(:template => 'welcome/plans')
  end

  def terms
  end

  def demos
    render(:template => 'welcome/demos')
  end

  def guides
  end
  
  def pricing
    redirect_to( :controller => 'welcome', :action => 'plans' )
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/epks_helper.rb
module EpksHelper
end

app/helpers/fact_sheets_helper.rb
module FactSheetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper


end

app/views/dashboard/_lead.html.haml
.row.lead
  .col-xs-6.col-md-3.leadphoto
    = image_tag "ball-puddle-e-col-hdr-2.png", :class => "thumbnail", :title => "Column Heading Graphic with Entreuse Logo Graphic"

  .col-xs-6.col-md-3
    %h4.rubic Category Indicator (1-2 words)
    %h3.header Leadline (3-6 words)
    %p.blurb Short blurb (4-6 words)

app/views/dashboard/construct.html.haml
#dashboard

  .panel
    %h2.panel-heading Construct Sheet for Dashboards and Viewers
    = render 'dashboard/lead'
 

app/views/dashboard/epkdashboard.html.haml
#dashboard
  %h1
    %em Dashboard
    /entruese/primary/
  .panel  
    .panel-heading
      
      
    .panel-body
      .row
        
        .col-md-9
          .row
            .col-xs-6.col-md-4
              .leadphoto
                = image_tag "entreuse-e-logo-color.png", :class => "img-rounded", :title => "Column Heading Graphic with Entreuse Logo Graphic"
    
            .col-xs-6.col-md-8.lead
              %h4.rubic Productivity Changer
              %h3.header A Whisper is Worth a Thousend Words
              %p.blurb
                Influencing the Influencers to attain your goals. Entreuse is a new type of electronic press kit, or EPK. Entreuse allows individuals and small enterprises with a product or service whether physical or electronically delivered, and who generally do not have regular access to publicity and marketing professional to use some of the tools availible to them. 
        
        .col-md-3.asset-box
          %h2 Asset/Index Box
        
      
      .epk-parts  
        .row
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Factsheet
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Screen Shots
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Who's Using It
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
      
        .row
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Factsheet
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Screen Shots
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
          .col-md-4
            .panel.part
              .panel-heading
                %h4 Who's Using It
              .panel-body
                %ul
                  %li list item 1
                  %li list item 2
                  %li list item 3
              .panel-footer
    
    .panel-footer
      %p= link_to "Edit EPK Factsheet", new_fact_sheet_path, class: "btn btn-default btn-md"
        

app/views/epks/_form.html.erb
<%= simple_form_for(@epk) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/epks/edit.html.erb
<h1>Editing epk</h1>

<%= render 'form' %>

<%= link_to 'Show', @epk %> |
<%= link_to 'Back', epks_path %>

app/views/epks/index.html.erb
<h1>Listing epks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @epks.each do |epk| %>
      <tr>
        <td><%= epk.name %></td>
        <td><%= epk.user_id %></td>
        <td><%= link_to 'Show', epk %></td>
        <td><%= link_to 'Edit', edit_epk_path(epk) %></td>
        <td><%= link_to 'Destroy', epk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Epk', new_epk_path %>

app/views/epks/new.html.erb
<h1>New epk</h1>

<%= render 'form' %>

<%= link_to 'Back', epks_path %>

app/views/epks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @epk.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @epk.user_id %>
</p>

<%= link_to 'Edit', edit_epk_path(@epk) %> |
<%= link_to 'Back', epks_path %>

app/views/fact_sheets/edit.html.erb
<div class="panel panel-primary panel-narrow">
  
  <div class="panel-heading">
    <h1>Editing fact_sheet</h1>
  </div>
  
  <div class="panel-body">
    <%= render 'form' %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Show', @fact_sheet %> |
    <%= link_to 'Back', fact_sheets_path %>
  </div>

</div>  
    

app/views/fact_sheets/index.htm.haml
<div class="panel panel-primary">
  
  <div class="panel-heading">
    <h1>Fact Sheet</h1>
  </div>
  
  <div class="panel-body">

    <table>
      <thead>
        <tr>
          <th>Vanity url</th>
          <th>Country</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Middle initial</th>
          <th>P k a</th>
          <th>Professional business type</th>
          <th>Client tel mobile</th>
          <th>Client tel work</th>
          <th>Client tel alt</th>
          <th>Client email alt</th>
          <th>Client url</th>
          <th>Client street address 1</th>
          <th>Client street address 2</th>
          <th>Client unit number</th>
          <th>Client city</th>
          <th>Client county</th>
          <th>Client state</th>
          <th>Client postal code</th>
          <th>Company name</th>
          <th>Company tel main</th>
          <th>Company url</th>
          <th>Company email</th>
          <th>Company street address 1</th>
          <th>Company street address 2</th>
          <th>Company suite number</th>
          <th>Company city</th>
          <th>Company county</th>
          <th>Company state</th>
          <th>Company postal code</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @fact_sheets.each do |fact_sheet| %>
          <tr>
            <td><%= fact_sheet.vanity_url %></td>
            <td><%= fact_sheet.country %></td>
            <td><%= fact_sheet.first_name %></td>
            <td><%= fact_sheet.last_name %></td>
            <td><%= fact_sheet.middle_initial %></td>
            <td><%= fact_sheet.p_k_a %></td>
            <td><%= fact_sheet.professional_business_type %></td>
            <td><%= fact_sheet.client_tel_mobile %></td>
            <td><%= fact_sheet.client_tel_work %></td>
            <td><%= fact_sheet.client_tel_alt %></td>
            <td><%= fact_sheet.client_email_alt %></td>
            <td><%= fact_sheet.client_url %></td>
            <td><%= fact_sheet.client_street_address_1 %></td>
            <td><%= fact_sheet.client_street_address_2 %></td>
            <td><%= fact_sheet.client_unit_number %></td>
            <td><%= fact_sheet.client_city %></td>
            <td><%= fact_sheet.client_county %></td>
            <td><%= fact_sheet.client_state %></td>
            <td><%= fact_sheet.client_postal_code %></td>
            <td><%= fact_sheet.company_name %></td>
            <td><%= fact_sheet.company_tel_main %></td>
            <td><%= fact_sheet.company_url %></td>
            <td><%= fact_sheet.company_email %></td>
            <td><%= fact_sheet.company_street_address_1 %></td>
            <td><%= fact_sheet.company_street_address_2 %></td>
            <td><%= fact_sheet.company_suite_number %></td>
            <td><%= fact_sheet.company_city %></td>
            <td><%= fact_sheet.company_county %></td>
            <td><%= fact_sheet.company_state %></td>
            <td><%= fact_sheet.company_postal_code %></td>
            <td><%= link_to 'Show', fact_sheet %></td>
            <td><%= link_to 'Edit', edit_fact_sheet_path(fact_sheet) %></td>
            <td><%= link_to 'Destroy', fact_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    
  </div>
  <div class="panel-footer">
    <%= link_to 'New Fact sheet', new_fact_sheet_path %>
  </div>

</div>  

app/views/fact_sheets/index.html.erb
<div class="panel panel-primary">
  
  <div class="panel-heading">
    <h1>Fact Sheet</h1>
  </div>
  
  <div class="panel-body">

    <table>
      <thead>
        <tr>
          <th>Vanity url</th>
          <th>Country</th>
          <th>First name</th>
          <th>Last name</th>
          <th>Middle initial</th>
          <th>P k a</th>
          <th>Professional business type</th>
          <th>Client tel mobile</th>
          <th>Client tel work</th>
          <th>Client tel alt</th>
          <th>Client email alt</th>
          <th>Client url</th>
          <th>Client street address 1</th>
          <th>Client street address 2</th>
          <th>Client unit number</th>
          <th>Client city</th>
          <th>Client county</th>
          <th>Client state</th>
          <th>Client postal code</th>
          <th>Company name</th>
          <th>Company tel main</th>
          <th>Company url</th>
          <th>Company email</th>
          <th>Company street address 1</th>
          <th>Company street address 2</th>
          <th>Company suite number</th>
          <th>Company city</th>
          <th>Company county</th>
          <th>Company state</th>
          <th>Company postal code</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
    
      <tbody>
        <% @fact_sheets.each do |fact_sheet| %>
          <tr>
            <td><%= fact_sheet.vanity_url %></td>
            <td><%= fact_sheet.country %></td>
            <td><%= fact_sheet.first_name %></td>
            <td><%= fact_sheet.last_name %></td>
            <td><%= fact_sheet.middle_initial %></td>
            <td><%= fact_sheet.p_k_a %></td>
            <td><%= fact_sheet.professional_business_type %></td>
            <td><%= fact_sheet.client_tel_mobile %></td>
            <td><%= fact_sheet.client_tel_work %></td>
            <td><%= fact_sheet.client_tel_alt %></td>
            <td><%= fact_sheet.client_email_alt %></td>
            <td><%= fact_sheet.client_url %></td>
            <td><%= fact_sheet.client_street_address_1 %></td>
            <td><%= fact_sheet.client_street_address_2 %></td>
            <td><%= fact_sheet.client_unit_number %></td>
            <td><%= fact_sheet.client_city %></td>
            <td><%= fact_sheet.client_county %></td>
            <td><%= fact_sheet.client_state %></td>
            <td><%= fact_sheet.client_postal_code %></td>
            <td><%= fact_sheet.company_name %></td>
            <td><%= fact_sheet.company_tel_main %></td>
            <td><%= fact_sheet.company_url %></td>
            <td><%= fact_sheet.company_email %></td>
            <td><%= fact_sheet.company_street_address_1 %></td>
            <td><%= fact_sheet.company_street_address_2 %></td>
            <td><%= fact_sheet.company_suite_number %></td>
            <td><%= fact_sheet.company_city %></td>
            <td><%= fact_sheet.company_county %></td>
            <td><%= fact_sheet.company_state %></td>
            <td><%= fact_sheet.company_postal_code %></td>
            <td><%= link_to 'Show', fact_sheet %></td>
            <td><%= link_to 'Edit', edit_fact_sheet_path(fact_sheet) %></td>
            <td><%= link_to 'Destroy', fact_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    
  </div>
  <div class="panel-footer">
    <%= link_to 'New Fact sheet', new_fact_sheet_path %>
  </div>

</div>  

app/views/fact_sheets/new.html.erb
<div class="container">
  <div class="panel panel-primary panel-narrow panel-center">
    
    <div class="panel-heading">
      <h1>Begin with Your Fact Sheet</h1>
    </div>
    
    <div class="panel-body">
      <%= render 'form' %>
    </div>
    
    <div class="panel-footer">
      <%= link_to 'Back', fact_sheets_path %>
    </div>
  </div>
</div>

app/views/fact_sheets/shared/_welcome_member.html.haml
%h2.text-center

  Welcome
  <%= @fact_sheet.first_name %>
  to Your
  <%= @fact_sheet.vanity_url %>
  Dashboard.
 

app/views/fact_sheets/show.html.erb
<div class="panel panel-primary panel-narrow">
  
  <div class="panel-heading">
    <h1>Fact Sheet for <%= @fact_sheet.vanity_url %>
      </h1>
  </div>
  
  <div class="panel-body">
    
   <p id="notice"><%= notice %></p>

<p>
  <strong>Vanity url:</strong>
  <%= @fact_sheet.vanity_url %>
</p>

<p>
  <strong>Country:</strong>
  <%= @fact_sheet.country %>
</p>

<p>
  <strong>First name:</strong>
  <%= @fact_sheet.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @fact_sheet.last_name %>
</p>

<p>
  <strong>Middle initial:</strong>
  <%= @fact_sheet.middle_initial %>
</p>

<p>
  <strong>P k a:</strong>
  <%= @fact_sheet.p_k_a %>
</p>

<p>
  <strong>Professional business type:</strong>
  <%= @fact_sheet.professional_business_type %>
</p>

<p>
  <strong>Client tel mobile:</strong>
  <%= @fact_sheet.client_tel_mobile %>
</p>

<p>
  <strong>Client tel work:</strong>
  <%= @fact_sheet.client_tel_work %>
</p>

<p>
  <strong>Client tel alt:</strong>
  <%= @fact_sheet.client_tel_alt %>
</p>

<p>
  <strong>Client email alt:</strong>
  <%= @fact_sheet.client_email_alt %>
</p>

<p>
  <strong>Client url:</strong>
  <%= @fact_sheet.client_url %>
</p>

<p>
  <strong>Client street address 1:</strong>
  <%= @fact_sheet.client_street_address_1 %>
</p>

<p>
  <strong>Client street address 2:</strong>
  <%= @fact_sheet.client_street_address_2 %>
</p>

<p>
  <strong>Client unit number:</strong>
  <%= @fact_sheet.client_unit_number %>
</p>

<p>
  <strong>Client city:</strong>
  <%= @fact_sheet.client_city %>
</p>

<p>
  <strong>Client county:</strong>
  <%= @fact_sheet.client_county %>
</p>

<p>
  <strong>Client state:</strong>
  <%= @fact_sheet.client_state %>
</p>

<p>
  <strong>Client postal code:</strong>
  <%= @fact_sheet.client_postal_code %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @fact_sheet.company_name %>
</p>

<p>
  <strong>Company tel main:</strong>
  <%= @fact_sheet.company_tel_main %>
</p>

<p>
  <strong>Company url:</strong>
  <%= @fact_sheet.company_url %>
</p>

<p>
  <strong>Company email:</strong>
  <%= @fact_sheet.company_email %>
</p>

<p>
  <strong>Company street address 1:</strong>
  <%= @fact_sheet.company_street_address_1 %>
</p>

<p>
  <strong>Company street address 2:</strong>
  <%= @fact_sheet.company_street_address_2 %>
</p>

<p>
  <strong>Company suite number:</strong>
  <%= @fact_sheet.company_suite_number %>
</p>

<p>
  <strong>Company city:</strong>
  <%= @fact_sheet.company_city %>
</p>

<p>
  <strong>Company county:</strong>
  <%= @fact_sheet.company_county %>
</p>

<p>
  <strong>Company state:</strong>
  <%= @fact_sheet.company_state %>
</p>

<p>
  <strong>Company postal code:</strong>
  <%= @fact_sheet.company_postal_code %>
</p>
</div>
  <div class="panel-footer"> 
<%= link_to 'Edit', edit_fact_sheet_path(@fact_sheet) %> |
<%= link_to 'Back', fact_sheets_path %>
  </div>

</div>

app/views/layouts/_footer.html.erb
<div class="footer-site">
  <p class="text-center">Entreuse&trade;<br>
    Copyright &copy; 2013 - 2014
     
      Mediapack, Inc., ALL RIGHTS RESERVED
  </p>
  <p class=text-center>Please report any broken links or any site functionality issues<br/>to the <%= link_to "Webmaster at Tenth Muse Creative", "http://tenthmusecreative.com/aboutContact/contact-form.php" %></p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Entreuse EPK', root_path, class: "navbar-brand navbar-brand-font" %>
    </div>
  
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li class="active">
          <%= link_to 'See Demo', demos_path %>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Go To<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
              <li><%= link_to 'My Dashboard', "#" %></li>
              <li><%= link_to 'Fact Sheet', "#" %></li>
              <li class="divider"></li>
              <li><%= link_to 'Guides', guides_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
               <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <% else %>
            <li><%= link_to 'Home', root_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Guides', guides_path %></li>
            <li class="divider"></li>
            <li><%= link_to 'Plans', plans_path %></li>
            <li><%= link_to "Terms", terms_path %></li>
            <li class="divider"></li>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Entreuse</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
  <body>

    <%= render 'layouts/header' %>
    
    <div class="container">
      
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>
    </div>

    
    <%= render 'layouts/footer' %>

  </body>
</html>

app/views/welcome/_badges.html.haml
.row
  .col-xs-12.col-sm-4.col-md-4.text-center
    %h4 Designed With
    = link_to image_tag("UXPin-logo-md.png", :title => "UXPin Logo", :class => "img-center img-responsive"), "http://uxpin.com/", :target => "_blank"
  
  .col-xs-12.col-sm-4.col-md-4.text-center
    %h4 Incubated by
    = link_to image_tag("fi-logo-w-typography-md.png", :title => "FI Graduates Badge", :class => "img-center img-responsive"), "http://fi.co/about", :target => "_blank"
  
  .col-xs-12.col-sm-4.col-md-4.text-center
    %h4 Ruby on Rails
    = link_to image_tag("onemorails-edu-logo-md.png", :title => "One Month Rails Badge", :class => "img-center img-responsive"), "http://fi.co/about", :target => "_blank"


app/views/welcome/guides.html.erb
<h1>Welcome#guides</h1>
<p>Find me in app/views/welcome/guides.html.erb</p>

app/views/welcome/index.html.erb
INDEX

app/views/welcome/plans.html.erb
<h1>Welcome#plans</h1>
<p>Find me in app/views/welcome/plans.html.erb</p>